### ISSUE TITLE
Definition of 'little words'

### ISSUE THREAD

**Issue by aalemayhu** [alexch/learn_ruby#25]
In the [simon_says_spec.rb](https://github.com/alexch/learn_ruby/blob/master/03_simon_says/simon_says_spec.rb#L87-L91) you use 'little words'. Could you please explain what you mean there?

**Comment by hunj** [comment]
I think `little words` mean words such as "and", "or", "nor", and so on. See [this English Stackexchange article](http://english.stackexchange.com/questions/14/which-words-in-a-title-should-be-capitalized)

**Comment by aalemayhu** [comment]
Seeing this now, thanks for explaining!
